version: '3'
services:
  dagster:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./pipelines:/opt/dagster/app/
      - ./data:/opt/dagster/data/
