version: '3'
services:
  dagster:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./medicine:/opt/dagster/dagster_home/medicine
      - ./data:/opt/dagster/data/
