version: 2

sources:
  - name: api
    tables:
      - name: raw_cards
        meta:
          dagster:
            asset_key: ["raw_cards"] # This metadata specifies the corresponding Dagster asset for this dbt source.
